--- # my loops play book
- hosts: all
  user: ansible
  become: true
  connection: ssh

  tasks:
    - name: installing multiple s/w's
      user: name='{{item}}' state=present
      with_items:
            - raj
            - ravi
            - appu
            - anil
            - hari
            - sudeep
