--- # my variable section
- hosts: all
  user: ansible
  become: yes
  connection: ssh

  vars:
    pkgname: httpd

  tasks:
    - name: install httpd s/w
      action: yum name='{{pkgname}}' state=installed

